=== brianhks/genormous/trunk/genormous/doc/tables_1.0.dtd
<!ELEMENT tables (table+)>
<!ELEMENT table (comment?,property*,col+)>
<!ATTLIST table
	name CDATA #REQUIRED
	>

<!ELEMENT comment (#PCDATA)>
<!ELEMENT property EMPTY>
<!ATTLIST property
	key CDATA #REQUIRED
	value CDATA #REQUIRED
	>

<!ELEMENT col (comment?,property*,reference?)>
<!ATTLIST col
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	primary_key CDATA "false"
	default_value CDATA #IMPLIED
	allow_null CDATA "true"
	unique CDATA "false"
	>
	
<!ELEMENT refernce EMPTY>
<!ATTLIST reference
	table CDATA #REQUIRED
	column CDATA #REQUIRED
	id CDATA #IMPLIED
	>

=== brianhks/genormous/trunk/genormous/test/test_project/tables.xml
<!DOCTYPE tables SYSTEM "http://genormous.googlecode.com/svn/trunk/genormous/doc/tables_1.0.dtd">

<tables>
	<table name="author">
		<property key="hsqldb_tableType" value="CACHED"/>
		<col name="author_id" type="integer" primary_key="true"/>
		<col name="name" type="string"/>
	</table>
	
	<table name="book">
		<property key="hsqldb_tableType" value="CACHED"/>
		<col name="author" type="integer">
			<reference table="author" column="author_id"/>
		</col>
		<col name="title" type="string"/>
		<col name="isbn" type="string"/>
	</table>
</tables>
